apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: trip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: poi
          image: registryvhk8886.azurecr.io/poi:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 256M
            limits:
              cpu: '1'
              memory: 1G
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: trip
spec:
  ports:
    - targetPort: 80
      name: port80
      port: 80
      protocol: TCP
  selector:
    app: poi
